apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-apps
  namespace: argocd
spec:
  project: production
  
  source:
    repoURL: https://github.com/lootopia-org/helm
    targetRevision: main
    path: applications/production
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
