apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
name: kafka
namespace: development
spec:
  kafka:
    version: 3.7.0
    replicas: 3
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      log.retention.hours: 168
      log.segment.bytes: 1073741824
    resources:
      requests:
        cpu: "2"
        memory: 2Gi
      limits:
        cpu: "2"
        memory: 4Gi
      jvmOptions:
        -Xms: 6g
        -Xmx: 6g
      rack:
        topologyKey: topology.kubernetes.io/zone
  zookeeper:
    replicas: 3
    resources:
      requests:
        cpu: "1"
        memory: 4Gi
      limits:
        cpu: "2"
      memory: 8Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}
