apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: dev-kafka
  namespace: development
spec:
  kafka:
    version: 3.7.0
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
    config:
      auto.create.topics.enable: "true"
  nodePools:
    - name: controllers
      replicas: 1
      roles:
        - controller
      storage:
        type: ephemeral
    - name: brokers
      replicas: 1
      roles:
        - broker
      storage:
        type: ephemeral
  entityOperator:
    topicOperator: {}

