apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 4.1.1
    nodePools:
      - name: kafka-pool-0
        replicas: 1
        storage:
          type: ephemeral
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}

